/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as AppOrgRouteRouteImport } from './routes/_app/$org/route'
import { Route as AppAppRouteImport } from './routes/_app/app'
import { Route as AppCreateRouteImport } from './routes/_app/create'
import { Route as AppOrgIndexRouteImport } from './routes/_app/$org/index'
import { Route as AppOrgCalendarRouteImport } from './routes/_app/$org/calendar'
import { Route as AppOrgLoremRouteImport } from './routes/_app/$org/lorem'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrgRouteRoute = AppOrgRouteRouteImport.update({
  id: '/$org',
  path: '/$org',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAppRoute = AppAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCreateRoute = AppCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrgIndexRoute = AppOrgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrgRouteRoute,
} as any)
const AppOrgCalendarRoute = AppOrgCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppOrgRouteRoute,
} as any)
const AppOrgLoremRoute = AppOrgLoremRouteImport.update({
  id: '/lorem',
  path: '/lorem',
  getParentRoute: () => AppOrgRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$org': typeof AppOrgRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/otp': typeof authOtpRoute
  '/app': typeof AppAppRoute
  '/create': typeof AppCreateRoute
  '/$org/calendar': typeof AppOrgCalendarRoute
  '/$org/lorem': typeof AppOrgLoremRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$org/': typeof AppOrgIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/otp': typeof authOtpRoute
  '/app': typeof AppAppRoute
  '/create': typeof AppCreateRoute
  '/$org/calendar': typeof AppOrgCalendarRoute
  '/$org/lorem': typeof AppOrgLoremRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$org': typeof AppOrgIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/$org': typeof AppOrgRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/otp': typeof authOtpRoute
  '/_app/app': typeof AppAppRoute
  '/_app/create': typeof AppCreateRoute
  '/_app/$org/calendar': typeof AppOrgCalendarRoute
  '/_app/$org/lorem': typeof AppOrgLoremRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/$org/': typeof AppOrgIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$org'
    | '/login'
    | '/otp'
    | '/app'
    | '/create'
    | '/$org/calendar'
    | '/$org/lorem'
    | '/api/auth/$'
    | '/$org/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/otp'
    | '/app'
    | '/create'
    | '/$org/calendar'
    | '/$org/lorem'
    | '/api/auth/$'
    | '/$org'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/$org'
    | '/(auth)/login'
    | '/(auth)/otp'
    | '/_app/app'
    | '/_app/create'
    | '/_app/$org/calendar'
    | '/_app/$org/lorem'
    | '/api/auth/$'
    | '/_app/$org/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authOtpRoute: typeof authOtpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$org': {
      id: '/_app/$org'
      path: '/$org'
      fullPath: '/$org'
      preLoaderRoute: typeof AppOrgRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/app': {
      id: '/_app/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAppRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/create': {
      id: '/_app/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AppCreateRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/$org/': {
      id: '/_app/$org/'
      path: '/'
      fullPath: '/$org/'
      preLoaderRoute: typeof AppOrgIndexRouteImport
      parentRoute: typeof AppOrgRouteRoute
    }
    '/_app/$org/calendar': {
      id: '/_app/$org/calendar'
      path: '/calendar'
      fullPath: '/$org/calendar'
      preLoaderRoute: typeof AppOrgCalendarRouteImport
      parentRoute: typeof AppOrgRouteRoute
    }
    '/_app/$org/lorem': {
      id: '/_app/$org/lorem'
      path: '/lorem'
      fullPath: '/$org/lorem'
      preLoaderRoute: typeof AppOrgLoremRouteImport
      parentRoute: typeof AppOrgRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppOrgRouteRouteChildren {
  AppOrgCalendarRoute: typeof AppOrgCalendarRoute
  AppOrgLoremRoute: typeof AppOrgLoremRoute
  AppOrgIndexRoute: typeof AppOrgIndexRoute
}

const AppOrgRouteRouteChildren: AppOrgRouteRouteChildren = {
  AppOrgCalendarRoute: AppOrgCalendarRoute,
  AppOrgLoremRoute: AppOrgLoremRoute,
  AppOrgIndexRoute: AppOrgIndexRoute,
}

const AppOrgRouteRouteWithChildren = AppOrgRouteRoute._addFileChildren(
  AppOrgRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppOrgRouteRoute: typeof AppOrgRouteRouteWithChildren
  AppAppRoute: typeof AppAppRoute
  AppCreateRoute: typeof AppCreateRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppOrgRouteRoute: AppOrgRouteRouteWithChildren,
  AppAppRoute: AppAppRoute,
  AppCreateRoute: AppCreateRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authOtpRoute: authOtpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
